# Generated by Django 3.2.7 on 2022-05-01 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GitAssessorApp', '0003_alter_checkedrules_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkedrules',
            name='user',
            field=models.CharField(max_length=150),
        ),
    ]
